/**
 * menu-data.js — Tala Restaurant & Café
 * ─────────────────────────────────────
 * Single source of truth for the entire menu.
 * Trilingual: Arabic (AR), English (EN), Sorani Kurdish (KU).
 * Last updated: 2026-04-19 — synced from official Excel menu sheet.
 */

/* ══════════════════════════════════════════════════════
   CATEGORIES
   Each entry generates: a navbar tab + a full menu section.
══════════════════════════════════════════════════════ */
const categories = [
  { id: 'breakfast',        title: 'فطور صباحي',        title_en: 'Breakfast',         title_ku: 'نانی بەیانیان',           icon: '🍳' },
  { id: 'soups',            title: 'شوربات',             title_en: 'Soups',             title_ku: 'شۆربا',                   icon: '🔥' },
  { id: 'cold_appetizers',  title: 'المقبلات الباردة',   title_en: 'Cold Appetizers',   title_ku: 'پێشخواردنی سارد',         icon: '🫕' },
  { id: 'salads',           title: 'السلطات',            title_en: 'Salads',            title_ku: 'زەڵاتەکان',               icon: '🥗' },
  { id: 'hot_appetizers',   title: 'مقبلات ساخنة',       title_en: 'Hot Appetizers',    title_ku: 'پێشخواردنی گەرم',         icon: '🍟' },
  { id: 'western',          title: 'اطباق غربية',        title_en: 'Western Dishes',    title_ku: 'خواردنی ڕۆژئاوایی',       icon: '🍽️' },
  { id: 'pasta',            title: 'الباستا',            title_en: 'Pasta',             title_ku: 'پاستا',                   icon: '🍝' },
  { id: 'sandwiches',       title: 'ساندوش',             title_en: 'Sandwiches',        title_ku: 'ساندویچ',                 icon: '🥪' },
  { id: 'eastern',          title: 'اطباق شرقية',        title_en: 'Eastern Dishes',    title_ku: 'خواردنی ڕۆژهەڵاتی',       icon: '🫙' },
  { id: 'grills',           title: 'مشاوي',              title_en: 'Grills',            title_ku: 'گۆشتی برژاو',             icon: '🔥' },
  { id: 'coffee',           title: 'البارستا',           title_en: 'Barista',           title_ku: 'باریستا',                 icon: '☕' },
  { id: 'desserts',         title: 'حلويات',             title_en: 'Desserts',          title_ku: 'شیرینییەکان',             icon: '🍰' },
  { id: 'arakel',           title: 'اراكيل',             title_en: 'Hookah',            title_ku: 'چوپوق',                   icon: '💨' },
  { id: 'juices',           title: 'عصائر طازجة',        title_en: 'Fresh Juices',      title_ku: 'شەربەتی فرێش',            icon: '🥤' },
];

/* ══════════════════════════════════════════════════════
   DISHES
   `category` must match a category id above.
══════════════════════════════════════════════════════ */
const dishes = [

  /* ── Breakfast ────────────────────────────────────── */
  {
    id: 'br1',
    category: 'breakfast',
    price: 20000,
    image: 'images/tala01.jpeg',
    name: 'سيت منيو فطور صباحي 2 شخص (عراقي)',
    name_en: 'Iraqi Breakfast Set – 2 Persons',
    name_ku: 'سێتی نانی بەیانی عێراقی – ٢ کەس',
    description: 'طاوه مخلمه لحم، طاوه بيض وطماطم، طاوه بيض وجبن، صحن بورك جبن، عروك طاوه، شوربه عدس، صحن ركي، لحم بعجين، مربا، جبن عرب، دبس تمر، راشي، قشطه، زيتون، لبن، عسل',
    description_en: 'Sautéed minced meat pan, egg & tomato pan, egg & cheese pan, cheese börek plate, lamb kofta pan, lentil soup, Iraqi bread, lahmacun, jam, Arab cheese, date molasses, tahini, clotted cream, olives, yoghurt, honey.',
    description_ku: 'تاوەی گۆشتی خاوکراو، تاوەی هێلکە و تەماتە، تاوەی هێلکە و پەنیر، بۆرەکی پەنیر، شۆربای نیسک، نانی عێراقی، گۆشتی لەسەر نان، مربا، پەنیری عەرەبی، شیرەی خورما، تاحین، قیمەر، زەیتون، ماست، هەنگوین.',
  },
  {
    id: 'br2',
    category: 'breakfast',
    price: 30000,
    image: 'images/tala01.jpeg',
    name: 'سيت منيو فطور صباحي 4 اشخاص (عراقي)',
    name_en: 'Iraqi Breakfast Set – 4 Persons',
    name_ku: 'سێتی نانی بەیانی عێراقی – ٤ کەس',
    description: 'صحن باقلاء بل دهن الحر، طاوه مخلمه لحم، طاوه بيض وطماطم، طاوه بيض وجبن، صحن بورك جبن، صحن عروك طاوه، شوربه عدس، صحن فواكه، لحم بعجين، مربا، جبن عرب، دبس تمر، راشي، قشطه، زيتون، لبن، عسل قيمر عرب، صحن كاهي',
    description_en: 'Fava beans with ghee, minced meat pan, egg & tomato pan, egg & cheese pan, cheese börek, lamb kofta pan, lentil soup, fruit platter, lahmacun, jam, Arab cheese, date molasses, tahini, clotted cream, olives, yoghurt, honey, Arab qaymar, kaahi plate.',
    description_ku: 'باقلا بە روون، تاوەی گۆشت، تاوەی هێلکە و تەماتە، تاوەی هێلکە و پەنیر، بۆرەکی پەنیر، شۆربای نیسک، بەستەی مێوە، گۆشتی لەسەر نان، مربا، پەنیری عەرەبی، شیرەی خورما، تاحین، قیمەر، زەیتون، ماست، هەنگوین، قەیمەر، کاهی.',
  },
  {
    id: 'br3',
    category: 'breakfast',
    price: 20000,
    image: 'images/tala02.jpeg',
    name: 'سيت منيو فطور صباحي 2 شخص (شامي)',
    name_en: 'Levantine Breakfast Set – 2 Persons',
    name_ku: 'سێتی نانی بەیانی شامی – ٢ کەس',
    description: 'شوربه عدس، فول، فته حمص، طاوه شكشوكه، طاوه بيض اعيون، جبن ضفاير، جبن كرات، زيتون، حمص، متبل باذنجان، لبنه، قشطه، مربا جزر، بيده، صحن ركي وفيتا',
    description_en: 'Lentil soup, fava beans, hummus fatteh, shakshuka pan, fried eggs pan, braided cheese, cheese balls, olives, hummus, smoky aubergine dip, labneh, clotted cream, carrot jam, tahini, bread with feta.',
    description_ku: 'شۆربای نیسک، فووڵ، فتەی حوموس، شەکشوکە، هێلکەی سرووشت، پەنیری ترینتراو، گووڵی پەنیر، زەیتون، حوموس، متبل، لەبنە، قیمەر، مربای زەردەک، تاحین، نان و فێتا.',
  },
  {
    id: 'br4',
    category: 'breakfast',
    price: 30000,
    image: 'images/tala03.jpeg',
    name: 'سيت منيو فطور صباحي 4 اشخاص (شامي)',
    name_en: 'Levantine Breakfast Set – 4 Persons',
    name_ku: 'سێتی نانی بەیانی شامی – ٤ کەس',
    description: 'شوربه عدس، فول، فته حمص، طاوه شكشوكه، طاوه بيض اعيون، طاوه مفركه، جبن ضفاير، جبن كرات، زيتون، حمص، متبل باذنجان، لبنه، قشطه، مكدوس، مربا جزر، بيده كبيره، صحن فواكه مشكل',
    description_en: 'Lentil soup, fava beans, hummus fatteh, shakshuka, fried eggs, scrambled eggs, braided cheese, cheese balls, olives, hummus, smoky aubergine dip, labneh, clotted cream, makdous, carrot jam, large tahini bowl, mixed fruit platter.',
    description_ku: 'شۆربای نیسک، فووڵ، فتەی حوموس، شەکشوکە، هێلکەی سرووشت، هێلکەی تێکەڵ، پەنیری ترینتراو، گووڵی پەنیر، زەیتون، حوموس، متبل، لەبنە، قیمەر، مەکدووس، مربای زەردەک، تاحینی گەورە، بەستەی مێوە.',
  },

  /* ── Soups ────────────────────────────────────────── */
  {
    id: 's1',
    category: 'soups',
    price: 3000,
    image: 'images/tala04.jpeg',
    name: 'شوربة عدس',
    name_en: 'Lentil Soup',
    name_ku: 'شۆربای نیسک',
    description: 'عدس، ليمون، خبز محمص',
    description_en: 'Smooth lentil soup served with lemon and toasted bread.',
    description_ku: 'شۆربای نیسکی نەرم لەگەڵ لیمۆ و نانی برژاو.',
  },
  {
    id: 's2',
    category: 'soups',
    price: 3000,
    image: 'images/tala05.jpeg',
    name: 'شوربة فطر',
    name_en: 'Mushroom Soup',
    name_ku: 'شۆربای فەقع',
    description: 'كريمه طبخ، جزر، بصل، زبده، فطر، بارميزان',
    description_en: 'Velvety cream of mushroom soup with carrots, onion, butter, and Parmesan.',
    description_ku: 'شۆربای کرێمی فەقع لەگەڵ زەردەک، پیاز، کەرە، و پارمەزان.',
  },
  {
    id: 's3',
    category: 'soups',
    price: 4000,
    image: 'images/tala06.jpeg',
    name: 'شوربة دجاج',
    name_en: 'Chicken Soup',
    name_ku: 'شۆربای مریشک',
    description: 'كريمه طبخ، جزر، بصل، زبده، فطر، بارميزان، دجاج',
    description_en: 'Creamy chicken soup with vegetables, mushrooms, butter, and Parmesan.',
    description_ku: 'شۆربای مریشکی کرێمی لەگەڵ سەوزەکان، فەقع، کەرە، و پارمەزان.',
  },

  /* ── Cold Appetizers ──────────────────────────────── */
  {
    id: 'ca1',
    category: 'cold_appetizers',
    price: 3500,
    image: 'images/tala07.jpeg',
    name: 'حمص',
    name_en: 'Hummus',
    name_ku: 'حوموس',
    description: 'حمص مسلوق، طحينية، ملح، ليمون، زيت زيتون',
    description_en: 'Silky blended chickpeas with tahini, lemon juice, and extra virgin olive oil.',
    description_ku: 'نۆکی کوڵاو لەگەڵ تاحین، ئاوی لیمۆ، و زەیتی زەیتوونی نایاب.',
  },
  {
    id: 'ca2',
    category: 'cold_appetizers',
    price: 4000,
    image: 'images/tala08.jpeg',
    name: 'متبل باذنجان',
    name_en: 'Baba Ganoush (Smoky Aubergine)',
    name_ku: 'متبەڵی باڵینجان',
    description: 'باذنجان مشوي، طحينيه، لبنه، عصير ليمون، ملح، ثوم مهروس، حب رمان',
    description_en: 'Fire-roasted aubergine blended with tahini, labneh, lemon, garlic, and pomegranate seeds.',
    description_ku: 'بادمجانی برژاو تێکەڵ بە تاحین، لەبنە، لیمۆ، سیر، و دانەی ئانار.',
  },
  {
    id: 'ca3',
    category: 'cold_appetizers',
    price: 3500,
    image: 'images/tala09.jpeg',
    name: 'بابا غنوج',
    name_en: 'Baba Ghanouj',
    name_ku: 'بابا غەنووج',
    description: 'باذنجان مشوي، خلطه خاصه',
    description_en: 'Char-grilled aubergine with our special house blend of spices and herbs.',
    description_ku: 'بادمجانی برژاو لەگەڵ تێکەڵەی تایبەتی خانووەکەمان.',
  },
  {
    id: 'ca4',
    category: 'cold_appetizers',
    price: 5000,
    image: 'images/tala10.jpeg',
    name: 'محمرة شركسية',
    name_en: 'Muhammara (Red Pepper Dip)',
    name_ku: 'مەحمەرە',
    description: 'دبس فليفله حلو، جوز عين جمل، عصير ليمون، دبس رمان، طحينيه',
    description_en: 'Roasted red pepper and walnut dip with lemon juice, pomegranate molasses, and tahini.',
    description_ku: 'تاحکراوەی فلیفلە سووری و ئێبالووی گەردوو لەگەڵ شیرەی ئانار و تاحین.',
  },
  {
    id: 'ca5',
    category: 'cold_appetizers',
    price: 4000,
    image: 'images/tala11.jpeg',
    name: 'متبل شونذر',
    name_en: 'Beetroot Dip',
    name_ku: 'متبەڵی چووندر',
    description: 'شونذر مسلوق، خلطه خاصه',
    description_en: 'Slow-boiled beetroot blended with our signature special spice mix.',
    description_ku: 'چووندری کوڵاو تێکەڵ بە بەهاراتی تایبەتی خانووەکەمان.',
  },
  {
    id: 'ca6',
    category: 'cold_appetizers',
    price: 6000,
    image: 'images/tala12.jpeg',
    name: 'صحن مقبلات مشكل',
    name_en: 'Mixed Appetizer Platter',
    name_ku: 'بەستەی پێشخواردن',
    description: 'متبل باذنجان، متبل شونذر، بابا غنوج، محمره شركسيه',
    description_en: 'A sharing platter featuring smoky aubergine, beetroot dip, baba ghanouj, and muhammara.',
    description_ku: 'بەستەیەک بۆ هاوبەشی لەگەڵ متبل، چووندر، بابا غەنووج، و مەحمەرە.',
  },
  {
    id: 'ca7',
    category: 'cold_appetizers',
    price: 6000,
    image: 'images/tala13.jpeg',
    name: 'حمص بلحمة',
    name_en: 'Hummus with Lamb',
    name_ku: 'حوموس بە گۆشتی مەڕ',
    description: 'حمص مسلوق، طحينية، ملح، ليمون، زيت زيتون، لوز صنوبري، لحم حبل ضهر، بصل',
    description_en: 'Creamy hummus topped with tender fillet of lamb, pine nuts, and caramelised onion.',
    description_ku: 'حوموسی نەرم لەگەڵ گۆشتی مەڕی نازک، دانەی چنارو، و پیازی کەرەمەل.',
  },
  {
    id: 'ca8',
    category: 'cold_appetizers',
    price: 5000,
    image: 'images/tala14.jpeg',
    name: 'ورق عنب',
    name_en: 'Stuffed Vine Leaves',
    name_ku: 'گەڵاکانی ترێ',
    description: 'ورق عنب، عصير ليمون، دبس رمان، حشوة خاصة، حب رمان',
    description_en: 'Tender vine leaves stuffed with our signature filling, drizzled with lemon juice and pomegranate molasses.',
    description_ku: 'گەڵاکانی ترێ پڕکراو لە تولدانی تایبەت، ئاوداوی لیمۆ و شیرەی ئانار.',
  },

  /* ── Salads ───────────────────────────────────────── */
  {
    id: 'sl1',
    category: 'salads',
    price: 7000,
    image: 'images/tala15.jpeg',
    name: 'سلطة كينوا',
    name_en: 'Quinoa Salad',
    name_ku: 'زەڵاتەی کینووا',
    description: 'خس، صوص خاص، كينوا، رمان، منكا، زبيب، جبنة فيتا، زعتر اخضر، لوز محمص، جرجير',
    description_en: 'Fresh lettuce with quinoa, pomegranate, mango, raisins, feta cheese, green thyme, toasted almonds, and rocket.',
    description_ku: 'کاهووی فرێش لەگەڵ کینووا، ئانار، مانگۆ، کشمیش، پەنیری فێتا، زعتری سەوز، بادامی برژاو، و جرجیر.',
  },
  {
    id: 'sl2',
    category: 'salads',
    price: 7000,
    image: 'images/tala16.jpeg',
    name: 'سلطة السيزر',
    name_en: 'Caesar Salad',
    name_ku: 'زەڵاتەی قەیسەر',
    description: 'خس، صوص السيزر، توست، جبنة بارميزان، دجاج، طماطم كرزية',
    description_en: 'Crisp romaine lettuce with Caesar dressing, croutons, Parmesan, grilled chicken, and cherry tomatoes.',
    description_ku: 'کاهووی ڕۆمانی لەگەڵ سۆسی قەیسەر، کرووتۆن، پارمەزان، مریشکی برژاو، و تەماتەی گیلاسی.',
  },
  {
    id: 'sl3',
    category: 'salads',
    price: 7000,
    image: 'images/tala17.jpeg',
    name: 'سلطة تمر',
    name_en: 'Date Salad',
    name_ku: 'زەڵاتەی خورما',
    description: 'تمر اسود، جوز عين الجمل، خس، جرجير، حب رمان، جبن فيتا، صوص خاص',
    description_en: 'Black dates, walnuts, fresh lettuce, rocket, pomegranate seeds, and feta cheese with a house dressing.',
    description_ku: 'خورمای ڕەش، گەردوو، کاهووی فرێش، جرجیر، دانەی ئانار، و پەنیری فێتا لەگەڵ سۆسی تایبەت.',
  },
  {
    id: 'sl4',
    category: 'salads',
    price: 6000,
    image: 'images/tala18.jpeg',
    name: 'سلطة جرجير',
    name_en: 'Rocket Salad',
    name_ku: 'زەڵاتەی جرجیر',
    description: 'جرجير، فطر، صوص خاص، شونذر، جبن بارميزان، رمان، بصل احمر، زيت زيتون، جوز عين الجمل',
    description_en: 'Peppery rocket with mushrooms, beetroot, Parmesan, pomegranate, red onion, olive oil, and walnuts.',
    description_ku: 'جرجیری تیژ لەگەڵ فەقع، چووندر، پارمەزان، ئانار، پیازی سووری، زەیتی زەیتوون، و گەردوو.',
  },
  {
    id: 'sl5',
    category: 'salads',
    price: 6000,
    image: 'images/tala07.jpeg',
    name: 'سلطة تبولة',
    name_en: 'Tabbouleh',
    name_ku: 'تەبووڵە',
    description: 'بقدونس، طماطم، بصل، برغل، ليمون، زيت زيتون، نعناع مجفف، كينوا بيضاء',
    description_en: 'Fresh parsley, tomatoes, onion, bulgur wheat, lemon, olive oil, dried mint, and white quinoa.',
    description_ku: 'بەقدووونسی فرێش، تەماتە، پیاز، بورغوڵ، لیمۆ، زەیتی زەیتوون، نەعنای وشک، و کینووای سپی.',
  },
  {
    id: 'sl6',
    category: 'salads',
    price: 5000,
    image: 'images/tala09.jpeg',
    name: 'سلطة فتوش',
    name_en: 'Fattoush',
    name_ku: 'فتووش',
    description: 'طماطم، خيار، خس، فجل، بقلة، دبس رمان، صوص خاص، نعناع، خبز مقرمش، زيتون',
    description_en: 'Tomatoes, cucumber, lettuce, radish, purslane, pomegranate molasses, mint, crispy pita bread, and olives.',
    description_ku: 'تەماتە، خیار، کاهوو، تەر، وەریوەلە، شیرەی ئانار، نەعنا، نانی کریسپی، و زەیتون.',
  },

  /* ── Hot Appetizers ───────────────────────────────── */
  {
    id: 'ha1',
    category: 'hot_appetizers',
    price: 3000,
    image: 'images/tala01.jpeg',
    name: 'فرايز',
    name_en: 'French Fries',
    name_ku: 'فرایز',
    description: 'بطاطا مقلية مع البهارات، صوص خاص',
    description_en: 'Golden crispy fries seasoned with signature spices, served with house dipping sauce.',
    description_ku: 'فرایزی زێڕین و کریسپی بە بەهاراتی تایبەت، لەگەڵ سۆسی خۆشی خانووەکەمان.',
  },
  {
    id: 'ha2',
    category: 'hot_appetizers',
    price: 6000,
    image: 'images/tala01.jpeg',
    name: 'كبدة بدبس الرمان',
    name_en: 'Chicken Liver with Pomegranate',
    name_ku: 'جیگەری مریشک بە شیرەی ئانار',
    description: 'كبده دجاج، بصل، ثوم، دبس رمان، رمان، بقدونس',
    description_en: 'Pan-seared chicken livers with onion, garlic, pomegranate molasses, fresh pomegranate seeds, and parsley.',
    description_ku: 'جیگەری مریشک لە تاوەدا لەگەڵ پیاز، سیر، شیرەی ئانار، دانەی ئانار، و بەقدووونس.',
  },
  {
    id: 'ha3',
    category: 'hot_appetizers',
    price: 10000,
    image: 'images/tala10.jpeg',
    name: 'دايناميت شرمب',
    name_en: 'Dynamite Shrimp',
    name_ku: 'شریمپی داینامایت',
    description: 'روبيان مقلي، صوص داينمت',
    description_en: 'Crispy fried shrimp tossed in a spicy dynamite sauce.',
    description_ku: 'شریمپی کریسپی لەگەڵ سۆسی داینامایتی توووچ.',
  },
  {
    id: 'ha4',
    category: 'hot_appetizers',
    price: 5000,
    image: 'images/tala01.jpeg',
    name: 'جيز رول',
    name_en: 'Cheese Roll',
    name_ku: 'رووڵی پەنیر',
    description: 'رقائق الفيلو، ثلاث انواع من الجبن، مربا الكرز، حبة البركه مع السمسم',
    description_en: 'Crispy phyllo rolls stuffed with three types of cheese, served with cherry jam and black seed & sesame topping.',
    description_ku: 'رووڵی فیلۆی کریسپی پڕکراو لە سێ جۆر پەنیر، لەگەڵ مربای گیلاس و دانەی ئاوائیە.',
  },
  {
    id: 'ha5',
    category: 'hot_appetizers',
    price: 4000,
    image: 'images/tala01.jpeg',
    name: 'بطاطا حارة',
    name_en: 'Spicy Potatoes',
    name_ku: 'پەتاتەی توووچ',
    description: 'مكعبات البطاطا، دبس فليفه، بقدونس، صوص خاص حد',
    description_en: 'Roasted potato cubes tossed with chilli paste, parsley, and our signature spicy house sauce.',
    description_ku: 'مکعبەکانی پەتاتە لەگەڵ پەستەی فلیفلە، بەقدووونس، و سۆسی توووچی تایبەت.',
  },

  /* ── Western Main Course ──────────────────────────── */
  {
    id: 'w1',
    category: 'western',
    price: 18000,
    image: 'images/tala01.jpeg',
    name: 'ستيك لحم',
    name_en: 'Beef Steak',
    name_ku: 'ستێکی گۆشت',
    description: 'لحم حبل الظهر مشوي، خضار سوتيه، بطاطا مهروسة، دومي كلاس صوص',
    description_en: 'Grilled sirloin steak with sautéed vegetables, creamy mashed potato, and demi-glace sauce.',
    description_ku: 'ستێکی سیرلۆینی برژاو لەگەڵ سەوزەی سووتێکراو، پووڕەی پەتاتە، و سۆسی دیمیگلاس.',
  },
  {
    id: 'w2',
    category: 'western',
    price: 13000,
    image: 'images/tala01.jpeg',
    name: 'ستيك دجاج',
    name_en: 'Chicken Steak',
    name_ku: 'ستێکی مریشک',
    description: 'صدر دجاج مشوي، خضار سوتيه، بطاطا مهروسة، صوص الفطر الابيض',
    description_en: 'Grilled chicken breast with sautéed vegetables, mashed potatoes, and white mushroom sauce.',
    description_ku: 'سینەی مریشکی برژاو لەگەڵ سەوزەی سووتێکراو، پووڕەی پەتاتە، و سۆسی فەقعی سپی.',
  },
  {
    id: 'w3',
    category: 'western',
    price: 12000,
    image: 'images/tala01.jpeg',
    name: 'فش اند شبس',
    name_en: 'Fish & Chips',
    name_ku: 'ماسی و چیپس',
    description: 'سمك فيليه مقرمش، بطاطا شبكية مقرمشة، صوص تارتار، بهارات خاصة',
    description_en: 'Crispy battered fish fillet with lattice-cut chips, tartare sauce, and special seasoning.',
    description_ku: 'فیلێی ماسی کریسپی لەگەڵ چیپسی بافلی، سۆسی تارتار، و بەهاراتی تایبەت.',
  },
  {
    id: 'w4',
    category: 'western',
    price: 13000,
    image: 'images/tala01.jpeg',
    name: 'دجاج بالفطر',
    name_en: 'Chicken with Mushroom',
    name_ku: 'مریشک بە فەقع',
    description: 'صدر دجاج، كريمه، فطر، بارميزان، بصل، كبسه رز، لوز',
    description_en: 'Pan-roasted chicken breast in a creamy mushroom and Parmesan sauce, served with saffron rice and almonds.',
    description_ku: 'سینەی مریشکی برژاو لە سۆسی کرێمی فەقع و پارمەزان، لەگەڵ برنجی زەعفەران و بادام.',
  },
  {
    id: 'w5',
    category: 'western',
    price: 12000,
    image: 'images/tala01.jpeg',
    name: 'بتر تشيكن',
    name_en: 'Butter Chicken',
    name_ku: 'بتەر چیکن',
    description: 'صدر دجاج، كريمه، كاجو، عصير طماطم، زبده، كرم ماسالا، كبسه رز',
    description_en: 'Tender chicken breast in a rich butter tomato sauce with cashews, cream, and garam masala, served with saffron rice.',
    description_ku: 'سینەی مریشک لە سۆسی تەماتە و کەرەی دەوڵەمەند لەگەڵ کاجوو و ماسالا، لەگەڵ برنجی زەعفەران.',
  },
  {
    id: 'w6',
    category: 'western',
    price: 12000,
    image: 'images/tala01.jpeg',
    name: 'دجاج كاري',
    name_en: 'Chicken Curry',
    name_ku: 'کاری مریشک',
    description: 'صدر دجاج، كريمه، بصل، طماطم، ثوم، حليب لوز، جبن بارميزان، كبسه رز',
    description_en: 'Chicken breast simmered in a fragrant curry sauce with onion, tomato, garlic, almond milk, and Parmesan, served with rice.',
    description_ku: 'سینەی مریشک لە سۆسی کاری بۆنخۆش لەگەڵ پیاز، تەماتە، سیر، شیری بادام، و پارمەزان.',
  },
  {
    id: 'w7',
    category: 'western',
    price: 13000,
    image: 'images/tala01.jpeg',
    name: 'فاهيتا لحم',
    name_en: 'Beef Fajita',
    name_ku: 'فاهیتای گۆشت',
    description: 'شرائح اللحم، بصل، فلفل الوان، صوص خاص، عصير حمضيات، كبسه رز',
    description_en: 'Sizzling beef strips with colourful peppers, onion, citrus sauce, and house seasoning, served with saffron rice.',
    description_ku: 'شریکەی گۆشت لەگەڵ فلیفلەی رەنگاوڕەنگ، پیاز، سۆسی حمضیات، لەگەڵ برنجی زەعفەران.',
  },
  {
    id: 'w8',
    category: 'western',
    price: 11000,
    image: 'images/tala01.jpeg',
    name: 'فاهيتا دجاج',
    name_en: 'Chicken Fajita',
    name_ku: 'فاهیتای مریشک',
    description: 'شرائح دجاج، بصل، فلفل الوان، صوص خاص، عصير حمضيات، كبسه رز',
    description_en: 'Sizzling chicken strips with peppers, onion, citrus sauce, and house seasoning, served with saffron rice.',
    description_ku: 'شریکەی مریشک لەگەڵ فلیفلەی رەنگاوڕەنگ، پیاز، و سۆسی حمضیات، لەگەڵ برنجی زەعفەران.',
  },

  /* ── Pasta ────────────────────────────────────────── */
  {
    id: 'p1',
    category: 'pasta',
    price: 12000,
    image: 'images/tala01.jpeg',
    name: 'بينيه ألفريدو',
    name_en: 'Penne Alfredo',
    name_ku: 'پێنێ ئەلفریدۆ',
    description: 'باستا بيني، دجاج، كريمة، فطر، بهارات خاصة، بارميزان',
    description_en: 'Penne pasta with grilled chicken in a velvety Alfredo cream sauce with mushrooms and Parmesan.',
    description_ku: 'پاستای پێنێ لەگەڵ مریشکی برژاو لە سۆسی ئەلفریدۆی کرێمی لەگەڵ فەقع و پارمەزان.',
  },
  {
    id: 'p2',
    category: 'pasta',
    price: 13000,
    image: 'images/tala01.jpeg',
    name: 'فيتوتشيني ألفريدو',
    name_en: 'Fettuccine Alfredo',
    name_ku: 'فیتووچینی ئەلفریدۆ',
    description: 'باستا فوتوتشيني، دجاج، كريمة، فطر، بهارات خاصة، بارميزان',
    description_en: 'Silky fettuccine with grilled chicken, cream, mushrooms, and Parmesan in a rich Alfredo sauce.',
    description_ku: 'فیتووچینی نەرم لەگەڵ مریشک، کرێم، فەقع، و پارمەزان لەگەڵ سۆسی ئەلفریدۆ.',
  },
  {
    id: 'p3',
    category: 'pasta',
    price: 12000,
    image: 'images/tala01.jpeg',
    name: 'بيستو باستا',
    name_en: 'Pesto Pasta',
    name_ku: 'پاستای پێستۆ',
    description: 'باستا بيني، كريمة، صوص ريحان الخاص، بارميزان، ريحان',
    description_en: 'Penne pasta tossed in a signature basil pesto cream sauce with Parmesan and fresh basil.',
    description_ku: 'پاستای پێنێ لەگەڵ سۆسی پێستۆی ریحانی تایبەت، پارمەزان، و ریحانی فرێش.',
  },
  {
    id: 'p4',
    category: 'pasta',
    price: 13000,
    image: 'images/tala01.jpeg',
    name: 'بينيه شيتوس',
    name_en: 'Cheetos Pasta',
    name_ku: 'پاستای چێتۆز',
    description: 'باستا بيني، كريمة، جبنة شيدر، شيبس شيتوس، دجاج',
    description_en: 'Penne pasta in a creamy cheddar sauce, topped with crispy Cheetos and tender chicken — a bold fusion dish.',
    description_ku: 'پاستای پێنێ لە سۆسی چێدەری کرێمی، لەگەڵ چێتۆزی کریسپی و مریشکی نازک.',
  },

  /* ── Sandwiches ───────────────────────────────────── */
  {
    id: 'sw1',
    category: 'sandwiches',
    price: 8000,
    image: 'images/tala01.jpeg',
    name: 'كلاسك برجر',
    name_en: 'Classic Burger',
    name_ku: 'بەرگری کلاسیک',
    description: 'شريحة لحم عراقي 150غ، صوص خاص، خس، طماطم، مخلل، فرايز، مشروب غازي',
    description_en: '150g Iraqi beef patty, house sauce, lettuce, tomato, pickles, fries, and a soft drink.',
    description_ku: '١٥٠غ گۆشتی عێراقی، سۆسی تایبەت، کاهوو، تەماتە، ترشیات، فرایز، و مشروبی گازی.',
  },
  {
    id: 'sw2',
    category: 'sandwiches',
    price: 9500,
    image: 'images/tala01.jpeg',
    name: 'مشروم برجر',
    name_en: 'Mushroom Burger',
    name_ku: 'بەرگری فەقع',
    description: 'شريحة لحم عراقي 150غ، صوص خاص، فطر، خليط اجبان، خس، طماطم، مخلل، فرايز، مشروب غازي',
    description_en: '150g beef patty, mushrooms, cheese blend, house sauce, lettuce, tomato, pickles, fries, and a soft drink.',
    description_ku: '١٥٠غ گۆشتی عێراقی، فەقع، تێکەڵەی پەنیر، کاهوو، تەماتە، ترشیات، فرایز، و مشروبی گازی.',
  },
  {
    id: 'sw3',
    category: 'sandwiches',
    price: 7000,
    image: 'images/tala01.jpeg',
    name: 'برجر دجاج',
    name_en: 'Chicken Burger',
    name_ku: 'بەرگری مریشک',
    description: 'شريحة دجاج 150غ، صوص خاص، خس، طماطم، مخلل، فرايز، مشروب غازي',
    description_en: '150g chicken patty, house sauce, lettuce, tomato, pickles, fries, and a soft drink.',
    description_ku: '١٥٠غ مریشک، سۆسی تایبەت، کاهوو، تەماتە، ترشیات، فرایز، و مشروبی گازی.',
  },
  {
    id: 'sw4',
    category: 'sandwiches',
    price: 7000,
    image: 'images/tala01.jpeg',
    name: 'شاورمة بايت',
    name_en: 'Shawarma Bite',
    name_ku: 'شاورمە بایت',
    description: 'خبز تورتيلا، شرائح دجاج متبل، ثوميه، مخلل، فرايز، سوسيرة ثوميه، فرايز جانبي، مشروب غازي',
    description_en: 'Marinated chicken strips in a flour tortilla with garlic sauce, pickles, and side fries — served with a soft drink.',
    description_ku: 'شریکەی مریشکی بەهاراتدار لە نانی تورتیلادا لەگەڵ سۆسی سیر، ترشیات، و فرایز، لەگەڵ مشروبی گازی.',
  },

  /* ── Eastern Main Course ──────────────────────────── */
  {
    id: 'e1',
    category: 'eastern',
    price: 20000,
    image: 'images/tala01.jpeg',
    name: 'قوزي لحم',
    name_en: 'Quzi (Slow-Roasted Lamb)',
    name_ku: 'قووزی گۆشتی مەڕ',
    description: 'لحم غنم عراقي، ثلاث انواع رز، فاصوليه، باميه، سلط شرقيه',
    description_en: 'Slow-roasted Iraqi lamb with three types of rice, green beans, okra, and an Eastern salad.',
    description_ku: 'گۆشتی مەڕی عێراقی بە هێواشی برژاو لەگەڵ سێ جۆر برنج، لووبیا، بامیە، و زەڵاتەی ڕۆژهەڵاتی.',
  },
  {
    id: 'e2',
    category: 'eastern',
    price: 14000,
    image: 'images/tala01.jpeg',
    name: 'مسخن فلسطيني',
    name_en: 'Musakhan (Palestinian Chicken)',
    name_ku: 'موساخان (مریشکی فەلەستینی)',
    description: 'دجاج متبل على الطريقه الفلسطينيه بالسماق، خبز، بصل، كبسه رز',
    description_en: 'Palestinian-style sumac-marinated roasted chicken on flatbread with caramelised onion and saffron rice.',
    description_ku: 'مریشکی برژاو بە شێوەی فەلەستینی بە سوماق، لەگەڵ نان، پیازی کەرەمەل، و برنجی زەعفەران.',
  },
  {
    id: 'e3',
    category: 'eastern',
    price: 19000,
    image: 'images/tala01.jpeg',
    name: 'كبسة لحم',
    name_en: 'Lamb Kabsa',
    name_ku: 'کەبسەی گۆشتی مەڕ',
    description: 'لحم غنم عراقي، رز كبسه، فاصوليه، باميه',
    description_en: 'Slow-cooked Iraqi lamb with aromatic kabsa rice, green beans, and okra.',
    description_ku: 'گۆشتی مەڕی عێراقی لەگەڵ برنجی کەبسەی بۆنخۆش، لووبیا، و بامیە.',
  },
  {
    id: 'e4',
    category: 'eastern',
    price: 14000,
    image: 'images/tala01.jpeg',
    name: 'كبسة دجاج',
    name_en: 'Chicken Kabsa',
    name_ku: 'کەبسەی مریشک',
    description: 'نصف دجاجه مشويه على الطريقه السعودية، رز كبسه، فاصوليه، باميه',
    description_en: 'Saudi-style half roasted chicken with kabsa rice, green beans, and okra.',
    description_ku: 'نیوی مریشکی برژاو بە شێوەی سعوودی لەگەڵ برنجی کەبسە، لووبیا، و بامیە.',
  },
  {
    id: 'e5',
    category: 'eastern',
    price: 16000,
    image: 'images/tala01.jpeg',
    name: 'برياني لحم',
    name_en: 'Lamb Biryani',
    name_ku: 'بریانی گۆشتی مەڕ',
    description: 'لحم غنم عراقي، رز برياني، شعريه، باميه، فاصوليه',
    description_en: 'Slow-cooked Iraqi lamb with aromatic biryani rice, vermicelli, okra, and green beans.',
    description_ku: 'گۆشتی مەڕی عێراقی بە هێواشی لەگەڵ برنجی بریانی، شعریە، بامیە، و لووبیا.',
  },
  {
    id: 'e6',
    category: 'eastern',
    price: 14000,
    image: 'images/tala01.jpeg',
    name: 'برياني دجاج',
    name_en: 'Chicken Biryani',
    name_ku: 'بریانی مریشک',
    description: 'دجاج، رز برياني، شعريه، باميه، فاصوليه',
    description_en: 'Tender chicken pieces with aromatic biryani rice, vermicelli, okra, and green beans.',
    description_ku: 'مریشکی نازک لەگەڵ برنجی بریانی، شعریە، بامیە، و لووبیا.',
  },
  {
    id: 'e7',
    category: 'eastern',
    price: 16000,
    image: 'images/tala01.jpeg',
    name: 'مقلوبة لحم',
    name_en: 'Lamb Maqluba',
    name_ku: 'مەقلووبەی گۆشتی مەڕ',
    description: 'لحم غنم عراقي، رز مقلوبه على الطريقه الفلسطينيه، باميه، فاصوليه',
    description_en: 'Iraqi lamb with Palestinian-style upside-down rice, okra, and green beans — a showstopping dish.',
    description_ku: 'گۆشتی مەڕی عێراقی لەگەڵ برنجی مەقلووبەی فەلەستینی، بامیە، و لووبیا.',
  },
  {
    id: 'e8',
    category: 'eastern',
    price: 12000,
    image: 'images/tala01.jpeg',
    name: 'مقلوبة دجاج',
    name_en: 'Chicken Maqluba',
    name_ku: 'مەقلووبەی مریشک',
    description: 'دجاج، رز مقلوبه على الطريقه الفلسطينيه، باميه، فاصوليه',
    description_en: 'Palestinian-style upside-down rice dish with tender chicken, okra, and green beans.',
    description_ku: 'برنجی مەقلووبەی فەلەستینی لەگەڵ مریشکی نازک، بامیە، و لووبیا.',
  },

  /* ── Grills ──────────────────────────────────────── */
  {
    id: 'gr1',
    category: 'grills',
    price: 14000,
    image: 'images/tala01.jpeg',
    name: 'سمك مسكوف',
    name_en: 'Masgouf (Iraqi BBQ Fish)',
    name_ku: 'ماسی مەسگووف',
    description: 'سمك مسكوف، رز احمر، صوص خاص، عمبة، خبز، طماطم، ليمون، جرجير',
    description_en: 'Iconic Iraqi open-fire barbecued fish, marinated and slow-grilled, served with red rice, mango pickle, bread, tomato, lemon, and rocket. (Price per Kilo)',
    description_ku: 'ماسی مەسگووفی کلاسیکی عێراقی لەسەر ئاگری کراوە پۆzkraوە، لەگەڵ برنجی سووری، عەمبە، نان، تەماتە، لیمۆ، و جرجیر پێشکەش دەکرێت. (نرخ بۆ کیلۆ)',
  },
  {
    id: 'gr2',
    category: 'grills',
    price: 22000,
    image: 'images/tala01.jpeg',
    name: 'دجاج تنور (كامل)',
    name_en: 'Tandoor Chicken (Whole)',
    name_ku: 'مریشکی تەنوور (تەواو)',
    description: 'دجاج تنور، خبز، صوص، رز، طماطم، ليمون، جرجير',
    description_en: 'Whole chicken marinated and cooked in a traditional clay tandoor, served with bread, sauce, rice, tomato, lemon, and rocket.',
    description_ku: 'مریشکی تەواو لە تەنووری گلین بەشێوەی نەریتی داپێچراو و برژاوکراوە، لەگەڵ نان، سۆس، برنج، تەماتە، لیمۆ، و جرجیر.',
  },
  {
    id: 'gr3',
    category: 'grills',
    price: 14000,
    image: 'images/tala01.jpeg',
    name: 'دجاج تنور (نصف دجاجة)',
    name_en: 'Tandoor Chicken (Half)',
    name_ku: 'مریشکی تەنوور (نیو)',
    description: 'دجاج تنور، خبز، صوص، رز، طماطم، ليمون، جرجير',
    description_en: 'Half chicken marinated and cooked in a traditional clay tandoor, served with bread, sauce, rice, tomato, lemon, and rocket.',
    description_ku: 'نیوی مریشک لە تەنووری گلین بەشێوەی نەریتی لەگەڵ نان، سۆس، برنج، تەماتە، لیمۆ، و جرجیر.',
  },

  /* ── Barista / Coffee ─────────────────────────────── */
  {
    id: 'c1',
    category: 'coffee',
    price: 3000,
    image: 'images/tala01.jpeg',
    name: 'اسبريسو مختص',
    name_en: 'Specialty Espresso',
    name_ku: 'ئێسپرێسۆی تایبەت',
    description: 'شوت مزدوج من حبوب القهوة الإثيوبية، مستخلصة بدقة لتبرز نكهات الحمضيات المشرقة والرائحة الزهرية.',
    description_en: 'A double-shot of single-origin Ethiopian Yirgacheffe beans, precision-extracted at 93°C — bright citrus notes and a floral aroma.',
    description_ku: 'دوو شۆت لە قاوەی ئەسیوبی، بە تامێکی نایاب و بۆنخۆش.',
  },
  {
    id: 'c2',
    category: 'coffee',
    price: 4000,
    image: 'images/tala01.jpeg',
    name: 'كولد برو',
    name_en: 'Cold Brew',
    name_ku: 'کۆڵد برو',
    description: 'قهوة كولومبية منقوعة على البارد لمدة 18 ساعة، قليلة الحموضة، ناعمة، وغنية بشكل مكثف.',
    description_en: '18-hour cold-steeped Colombian beans — low-acid, smooth, and intensely rich, served over ice.',
    description_ku: 'قاوەی کۆڵۆمبی بۆ ماوەی ١٨ کاتژمێر لە ئاوی سارددا دەمێندرێتەوە، بە سەهۆڵ و کەمێک کرێم.',
  },
  {
    id: 'c3',
    category: 'coffee',
    price: 4500,
    image: 'images/tala01.jpeg',
    name: 'كابتشينو بالزعفران',
    name_en: 'Saffron Cappuccino',
    name_ku: 'کاپوچینۆ بە زەعفەران',
    description: 'مزيج فاخر من الإسبريسو ورغوة الحليب الدقيقة الممزوجة بخلاصة الزعفران الفارسي الأصلي.',
    description_en: 'A luxurious blend of espresso and micro-foam infused with genuine Persian saffron, dusted with cinnamon and gold flakes.',
    description_ku: 'تێکەڵەیەکی نایاب لە ئێسپرێسۆ و کەفی شیرین لەگەڵ تامی زەعفەرانی ئەسڵی و دارچین.',
  },

  /* ── Desserts ─────────────────────────────────────── */
  {
    id: 'd1',
    category: 'desserts',
    price: 9000,
    image: 'images/tala01.jpeg',
    name: 'بقلاوة تركية',
    name_en: 'Turkish Baklava',
    name_ku: 'بەقلاوەی تورکی',
    description: 'طبقات مقرمشة من عجينة الفيلو المحشوة بالفستق الحلبي، والمحلاة بقطر الفانيليا.',
    description_en: 'Crispy phyllo layers generously filled with pistachios and sweetened with fragrant vanilla syrup.',
    description_ku: 'چینە کریسپییەکانی هەویری فیلۆ پڕکراوی فستق لەگەڵ شرووبی ڤانێلا.',
  },

  /* ── Juices ───────────────────────────────────────── */
  {
    id: 'j1',
    category: 'juices',
    price: 3000,
    image: 'images/tala01.jpeg',
    name: 'عصير برتقال طازج',
    name_en: 'Fresh Orange Juice',
    name_ku: 'شەربەتی پڕتەقاڵی فرێش',
    description: 'عصير برتقال فالنسيا المعصور طازجاً، بدون أية إضافات.',
    description_en: 'Pure freshly squeezed Valencia oranges — nothing added, nothing taken away.',
    description_ku: 'شەربەتی پڕتەقاڵی تازە گووشراو، هیچ شتێکی بۆ زیادنەکراوە.',
  },
  {
    id: 'j2',
    category: 'juices',
    price: 2500,
    image: 'images/tala01.jpeg',
    name: 'عصير رقي (بطيخ)',
    name_en: 'Watermelon Juice',
    name_ku: 'شەربەتی شووتی',
    description: 'عصير بطيخ أحمر طازج مع لمسة من الليمون، منعش وحلو المذاق.',
    description_en: 'Cold-pressed fresh watermelon with a hint of lime zest — hydrating and brilliantly pink.',
    description_ku: 'شەربەتی شووتی فرێش لەگەڵ کەمێک لیمۆ، شیرین و تامبەخش.',
  },
  {
    id: 'j3',
    category: 'juices',
    price: 4500,
    image: 'images/tala01.jpeg',
    name: 'ديتوكس أخضر',
    name_en: 'Green Detox',
    name_ku: 'دیتۆکسی سەوز',
    description: 'سبانخ، خيار، تفاح، زنجبيل، وليمون معصور على البارد في عصير أخضر حيوي.',
    description_en: 'Spinach, cucumber, apple, ginger, and lemon cold-pressed into a lively green juice — clean, crisp, and energising.',
    description_ku: 'سپێناخ، خەیار، سێو، زەنجەبیل، و لیمۆ تێکەڵەیەک لە شەربەتی سەوزی تەندروست.',
  },
  {
    id: 'j4',
    category: 'juices',
    price: 3500,
    image: 'images/tala01.jpeg',
    name: 'فيرجن موهيتو',
    name_en: 'Virgin Mojito',
    name_ku: 'مۆجیتۆ',
    description: 'مزيج منعش من عصير الليمون الطازج، أوراق النعناع المهروسة، قصب السكر، والمياه الفوارة على الثلج المجروش.',
    description_en: 'Refreshing blend of fresh lime juice, muddled mint leaves, cane sugar, and sparkling water over crushed ice.',
    description_ku: 'تێکەڵەیەکی فرێش لە ئاوی لیمۆی تازە، گەڵای نەعنا، شەکر، و ئاوی گازی لەگەڵ سەهۆڵ.',
  },
];

/* ══════════════════════════════════════════════════════
   EXCELLENCE CAROUSEL ITEMS
   Special highlighted items for the top carousel.
══════════════════════════════════════════════════════ */
const excellenceItems = [
  'gr1', // Masgouf
  'e1',  // Quzi Lamb
  'w1',  // Beef Steak
  'c3',  // Saffron Cappuccino
];
